# Generated by Django 5.2.4 on 2025-07-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_oaaprofile_orgprofile_studentprofile_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='completed_service_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='penalty_service_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='required_service_hours',
            field=models.FloatField(default=20.0),
        ),
    ]
