# Generated by Django 5.2.4 on 2025-07-16 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studentprofile_completed_service_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='id_number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('service_hours', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
                ('role_descriptions', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('approved', models.BooleanField(default=False)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.orgprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(related_name='events', through='core.Participation', to='core.studentprofile'),
        ),
    ]
