# Generated by Django 5.2.4 on 2025-07-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_classschedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('student', 'event')},
        ),
    ]
